### ISSUE TITLE
Proposal: Add Competing Consumers

### ISSUE THREAD

**Issue by vectorhacker** [jetbasrawi/go.geteventstore#11]
It would be nice to add competing consumers to the go API. I think it would be a simple addition using the HTTP API.

**Comment by jetbasrawi** [comment]
Yes. I have no objection. If someone doesn't contribute it, I will do it at some stage.

**Comment by vectorhacker** [comment]
I would be more than happy to help. It's something I have a vested interest on, since it would make my query side projections muuuch easier.

**Comment by jetbasrawi** [comment]
Any update on this?

**Comment by vectorhacker** [comment]
Sorry, haven't had time to work on this.

**Comment by vectorhacker** [comment]
@jetbasrawi I started a new project client for event store, I created some interfaces for event reading, writing and streaming. I'm adding competing consumers now. [issue #2](https://github.com/vectorhacker/goro/issues/2) on my project. You're welcome to contribute if you wish and comment on my models.
