### ISSUE TITLE
Next() does returns current event.

### ISSUE THREAD

**Issue by bweston92** [jetbasrawi/go.geteventstore#12]
Here is my code, it pulls an event (which is a Click) and the next time it pulls the next event in the stream. However I get the same event back every time.

I can only get it wokring by storing a local version and calling `NextVersion(r.version++)` every time.

Here is my Next method which calls the stream readers next function.
```
func (r *Reader) Next() (*stream.Click, error) {
	r.lock.Lock()
	defer r.lock.Unlock()

	if !r.client.Next() {
		return nil, io.EOF
	}

	if err := r.client.Err(); err != nil {
		if _, ok := err.(*goes.ErrNoMoreEvents); ok {
			return nil, io.EOF
		}

		return nil, err
	}

	o := &stream.Click{}
	return o, r.client.Scan(&o, nil)
}
```

**Comment by bweston92** [comment]
Whoops sorry had a crazy moment!

**Comment by lowewenzel** [comment]
Hey @bweston92, what solved this? I'm trying the long poll option, but when the application starts, it shows 4 events at the head of the stream. I'd like to just get new ones to pop up.
