### ISSUE TITLE
Successful response but no event

### ISSUE THREAD

**Issue by Brandon2255p** [jetbasrawi/go.geteventstore#16]
Hi I like the simplicity of this library so thank you very much.
I have an issue where I am appending an event but most of the time it does not appear in the EventStore

The EventStore log shows this:
![image](https://user-images.githubusercontent.com/8842924/78451927-a9864400-7688-11ea-94c1-14930e1299fc.png)

My source code is here if you would be able to take a look
github.com/Brandon2255p/watermill-eventstore/eventstore

**Comment by Brandon2255p** [comment]
Ah I see that go caches test results and that is why it never re-emitted events! 
Closing

**Comment by jetbasrawi** [comment]
Glad you got it sorted. Thanks for the kind words.
