### ISSUE TITLE
NextVersion

### ISSUE THREAD

**Issue by samidalouche** [jetbasrawi/go.geteventstore#2]
Hi,

for some reason, calling NextVersion does not seem to start reading at the given offset.

Let's say I have 5 events in a stream (EventStore 3.8.x), and I execute

```go
     requestReader := commandListener.EventStoreClient.NewStreamReader(requestsStreamName)
     requestReader.NextVersion(3)

     for requestReader.Next() {
         if requestReader.Err() != nil {
             panic("error")
	} else {
            log.WithFields(logrus.Fields{
		"currentEvent": requestReader.EventResponse().Event.EventNumber,
	 }).Info("Current Event")
        }
     }
```

I get the output :

```
Current Event currentEvent=0
Current Event currentEvent=1
Current Event currentEvent=2
Current Event currentEvent=3
```

In addition, if I pick a `NextVersion` higher than the default page size (`20`), it is not restarting from 0.

I can see that there is an automated test asserting that this works, but for some reason running the tests complains on my machine about the internal uuid package.

**Comment by samidalouche** [comment]
After recreating my environment (glide, ...), it seems that things are working, so I may have run with an older version, or something like that... In any case, it seems to work now...

BTW, do you have setup instructions to explain how to run the unit tests? It would be useful to reproduce issues and report issues

**Comment by jetbasrawi** [comment]
Hi sami, sorry I was travelling and only just seen your issue. 

Glad you got it sorted. 

To run unit tests, you will need to get the dependencies. 

https://github.com/jetbasrawi/go.geteventstore.testfeed
and 
https://gopkg.in/check.v1

After that it should be just the usual go test
